name: dart_tags
description: A dart library for work with id3 tags.
version: 0.0.1
#homepage: https://github.com/NiKoTron/dart-tags
#author: NiKoTron <nickolay.simonov@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
