name: dart_tags
description: A dart library for work with music tags like ID3.
version: 0.0.2
homepage: https://github.com/NiKoTron/dart-tags
author: NiKoTron <nickolay.simonov@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
